services:
  - type: web
    name: app-gastos-frontend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    branch: main
    envVars:
      - key: VITE_API_URL
        value: https://app-gastos-api-wyks.onrender.com/api

