// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/movimientos": {
    params: {};
  };
  "/dashboard/gastos": {
    params: {};
  };
  "/dashboard/ingresos": {
    params: {};
  };
  "/dashboard/perfil": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/dashboard" | "/dashboard/movimientos" | "/dashboard/gastos" | "/dashboard/ingresos" | "/dashboard/perfil" | "/*";
  };
  "pages/LandingPage.jsx": {
    id: "pages/LandingPage";
    page: "/";
  };
  "pages/LoginPage.jsx": {
    id: "pages/LoginPage";
    page: "/login";
  };
  "pages/RegisterPage.jsx": {
    id: "pages/RegisterPage";
    page: "/register";
  };
  "routes/ProtectedRoute.jsx": {
    id: "routes/ProtectedRoute";
    page: "/dashboard" | "/dashboard/movimientos" | "/dashboard/gastos" | "/dashboard/ingresos" | "/dashboard/perfil";
  };
  "layouts/DashboardLayout.jsx": {
    id: "layouts/DashboardLayout";
    page: "/dashboard" | "/dashboard/movimientos" | "/dashboard/gastos" | "/dashboard/ingresos" | "/dashboard/perfil";
  };
  "pages/DashboardPage.jsx": {
    id: "pages/DashboardPage";
    page: "/dashboard";
  };
  "pages/MovimientosPage.jsx": {
    id: "pages/MovimientosPage";
    page: "/dashboard/movimientos";
  };
  "pages/GastosPage.jsx": {
    id: "pages/GastosPage";
    page: "/dashboard/gastos";
  };
  "pages/IngresosPage.jsx": {
    id: "pages/IngresosPage";
    page: "/dashboard/ingresos";
  };
  "pages/ProfilePage.jsx": {
    id: "pages/ProfilePage";
    page: "/dashboard/perfil";
  };
  "routes/NotFound.jsx": {
    id: "routes/NotFound";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.jsx");
  "pages/LandingPage": typeof import("./src/pages/LandingPage.jsx");
  "pages/LoginPage": typeof import("./src/pages/LoginPage.jsx");
  "pages/RegisterPage": typeof import("./src/pages/RegisterPage.jsx");
  "routes/ProtectedRoute": typeof import("./src/routes/ProtectedRoute.jsx");
  "layouts/DashboardLayout": typeof import("./src/layouts/DashboardLayout.jsx");
  "pages/DashboardPage": typeof import("./src/pages/DashboardPage.jsx");
  "pages/MovimientosPage": typeof import("./src/pages/MovimientosPage.jsx");
  "pages/GastosPage": typeof import("./src/pages/GastosPage.jsx");
  "pages/IngresosPage": typeof import("./src/pages/IngresosPage.jsx");
  "pages/ProfilePage": typeof import("./src/pages/ProfilePage.jsx");
  "routes/NotFound": typeof import("./src/routes/NotFound.jsx");
};